/**
 * Lista de exercícios pré cadastradas
 */
let LISTA_STR = `
AFUNDO COM BARRA
AGACHAMENTO HACK INVERTIDO
AFUNDO NO SMITH MACHINE
AGACHAMENTO BULGARO
AGACHAMENTO COM HALTERES
AGACHAMENTO FRENTE COM BARRA LIVRE
AGACHAMENTO FRENTE NO SMITH MACHINE
AGACHAMENTO LIVRE
AGACHAMENTO NO HACK
AGACHAMENTO NO SMITH MACHINE (PÉS NA LARGURA DOS OMBROS)
AGACHAMENTO NO SMITH MACHINE (PÉS UNIDOS)
AGACHAMENTO NO SMITH MACHINE (PERNAS AFASTADAS)
AGACHAMENTO SPLIT
CADEIRA EXTENSORA
CADEIRA EXTENSORA UNILATERAL
LEG PRESS 45°
LEG PRESS 45° PÉS AFASTADOS NO ALTO DA PLATAFORMA
LEG PRESS 45° PÉS NO CENTRO DA PLATAFORMA
LEG PRESS 45° PÉS PRÓXIMOS NO INÍCIO DA PLATAFORMA
LEG PRESS 45° UNILATERAL
LEG PRESS HORIZONTAL 
PASSADA COM BARRA 
SISSY SQUAT
CADEIRA FLEXORA
FLEXOR UNILATERAL
FLEXOR VERTICAL COM CANELEIRAS
MESA FLEXORA
MESA FLEXORA UNILATERAL
STIFF COM BARRA
STIFF COM HALTERES
FLEXÃO PLANTAR EM PÉ SMITH MACHINE 
FLEXÃO PLANTAR MÁQUINA
FLEXÃO PLANTAR NO HACK MACHINE
FLEXÃO PLANTAR NO LEG PRESS 45°
FLEXÃO PLANTAR UNILATERAL NO LEG PRESS 45°
FLEXÃO PLANTAR NO LEG PRESS HORIZONTAL
FLEXÃO PLANTAR SENTADO
FLEXÃO PLANTAR SOB UM STEP
FLEXÃO PLANTAR UNILATERAL SOB STEP
`;


const LISTA_EXERCICIOS_INICIAL = [];

//LISTA_EXERCICIOS_INICIAL.forEach

LISTA_STR = [...LISTA_STR.split('\n')];
for (let i = 0 ; i < LISTA_STR.length ; i++) {
    LISTA_STR[i] = LISTA_STR[i].trim();
    if (LISTA_STR[i])
        LISTA_EXERCICIOS_INICIAL.push(LISTA_STR[i]);
}
LISTA_EXERCICIOS_INICIAL.sort();
LISTA_STR = null;

export default LISTA_EXERCICIOS_INICIAL;
